
# Copyright (c) 2016 Intel Corporation. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

sudo: false

os:
- linux

language: android

android:
  components:
  - build-tools-22.0.1
  - android-22

env:
  matrix:
  - XWALK_CHANNEL=canary XWALK_VERSION=18.46.466.0

before_install:
- cd ..

install:
- git config --global user.email "minggangw@gmail.com"
- git config --global user.name "Minggang Wang"
# Install depot_tools
- git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git `pwd`/src/third_party/depot_tools
- export PATH="$PATH":`pwd`/src/third_party/depot_tools
# Install GYP
- git clone https://chromium.googlesource.com/external/gyp `pwd`/src/third_party/gyp
- export PATH="$PATH":`pwd`/src/third_party/gyp
# Download Crosswalk
- curl -LO https://download.01.org/crosswalk/releases/crosswalk/android/${XWALK_CHANNEL}/${XWALK_VERSION}/crosswalk-${XWALK_VERSION}.zip
  && unzip crosswalk-${XWALK_VERSION}.zip && rm crosswalk-${XWALK_VERSION}.zip
- chmod a+x `pwd`/crosswalk-${XWALK_VERSION}/make_apk.py
- export PATH="$PATH":`pwd`/crosswalk-${XWALK_VERSION}
- export PATH="$PATH":/usr/local/android-sdk/build-tools/22.0.1
- export GYP_GENERATORS='ninja'

before_deploy:
- zip -j iap.zip out/Default/gen/iap/iap.jar out/Default/gen/iap/iap.js out/Default/gen/iap/iap.json

deploy:
  provider: releases
  api_key:
    secure: Hqb/uvFY21dlxEfAceuu7wsfvo2+vsMRfl+34KYlrA5e6h987ev7UDWrmfte2MXOgiesCS7iaZaUQc3HGwMT96bP4GJY9lcJt5S29Ohjaopno1DgwUTXhMQ5Ls/a0+QxHgtGrPgUkYGoFtHjpVspneOGUbMmou9EmRdqL0ZbOwc4ihSvof2rMvZvI07dNf57gzUoBZDLpwuBDYyymnVZkth582UUOv4xUv1/jJikLZShIadgXS+ZpjLWsdgZyPzmtD/8bSnou6PIwserVwSJ6q3N67p/dWNKEvXA+NBmNoGYY3SuvsmtCimSY68/u6GCtcaE85P6p5HcIhrKCsRfkbjczOiduob1qnGz+2VnREzVe2z0+Df2elutm5JT8qax6pNTwjCKWwasrnSynCST1It32qGQ+v41ufYcLdP434kliN0cofsMW0VJ6rC7uWj7UvTeynKWOkf58ZLGEyIBsxb2KRS8ELay3TUN1ZNSwsqSL7zdBswH868vxHlpxpKi46WIY1fgVQk714woQerRflQHTsqJGMp/fYRyxo1MO0SvqVQH4btUr2v+PfyoIr8fzqGuP69vTG7vE7IKPfyB/9N8BGcBZqQmK1WcX6wDJMWYbWzrF2L8GACoPlTnf/bYYpRkd6SGNZeRUvQVpkvcdfAUnt3+mnMXgpAuvP8J6lY=
  file:
  - iap.zip
  skip_cleanup: true
  on:
    tags: true

script:
- cd crosswalk-android-extensions
- gyp --depth=. all.gyp
- ninja -C out/Default pack_iap_jars

notifications:
  email:
    recipients:
    - minggang.wang@intel.com
    on_success: always
    on_failure: always
